### ISSUE TITLE
API-requests loop after searching for a movie

### ISSUE THREAD

**Issue by fidelisrafael** [alexmanzo/movie-search-vuejs#1]
Hey there, how it's going?

I just stumbled in this project of yours, and during my tests, I found out that after searching for a movie, the application keeps an open loop which sends numerous requests to the "MovieDB API" until it gets limited by the rate limit on the API side.

![movie-search-vue-search](https://user-images.githubusercontent.com/1542608/50466637-e9d71c80-0985-11e9-9184-93c32f0ee811.png)

This a nice project, I am too sleepy right now to send a PR, so that's why I am opening a issue.

**Comment by fidelisrafael** [comment]
I am not sure, but maybe the problem [is here](https://github.com/alexmanzo/movie-search-vuejs/blob/master/src/components/searchResults.vue#L60).

Perhaps this `beforeUpdate` method is called in every DOM rendering?(And sometimes tons of renders can happen in a few `ms`). I never worked with Vue.js  so I'm not sure, just trying to figure it out looking at the code.

**Comment by alexmanzo** [comment]
Hey! Thanks for pointing this out. For whatever reason, I didn't see it until now. That was a problem I ran into during development and thought I had squashed it, but I'll jump back in and have a look!
